#!/bin/bash

ip=192.168.10.42
port=5555

while true; do
    if nc -z -w 4 $ip $port; then
        #adb disconnect $ip:$port
        #adb connect $ip:$port
        adbcon.sh
        #adb -s $ip:$port logcat -v time | grep "start playing .*"
        adb -s $ip:$port logcat  | grep kiban18
        #adb -s $ip:$port logcat PTSPopulator:S | grep kiban18
    else
        echo waiting adbd...
        sleep 1;
    fi
done
